name: Pipeline testes regressivos - Web

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron:  '0 0 * * FRI'

jobs: 
  e2e-tests: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
          sudo apt-get update
          sudo apt-get install google-chrome-stable

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test
