name: Pipeline testes regressivos - Web

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron:  '0 0 * * FRI'

jobs: 
  e2e-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set ChromeDriver Version
        run: export CHROMEDRIVER_VERSION="120.0.6099.199"

      - name: Install ChromeDriver
        run: |
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
